name: Update total downloads

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # важно!
          fetch-depth: 0              # чтобы была вся история

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python3 scripts/update_downloads.py
          git add .
          git commit -m "chore: update total downloads badge" || echo "No changes to commit"
          git push
